-- MySQL Script generated by MySQL Workbench
-- Fri Sep 16 20:55:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oficina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oficina` DEFAULT CHARACTER SET utf8 ;
USE `oficina` ;

-- -----------------------------------------------------
-- Table `oficina`.`cardPayments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`cardPayments` (
  `idcardPayments` INT NOT NULL,
  `cvv` INT(5) NULL,
  `number_card` INT(15) NULL,
  `valid_card` VARCHAR(15) NULL,
  `type_card` ENUM('debit', 'credit') NULL DEFAULT 'debit',
  PRIMARY KEY (`idcardPayments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`payments` (
  `idpayments` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type_payments` ENUM('ticket', 'cash', 'card') NULL DEFAULT 'cash',
  `cardPayments_idcardPayments` INT NOT NULL,
  PRIMARY KEY (`idpayments`, `cardPayments_idcardPayments`),
  INDEX `fk_payments_cardPayments1_idx` (`cardPayments_idcardPayments` ASC) VISIBLE,
  CONSTRAINT `fk_payments_cardPayments1`
    FOREIGN KEY (`cardPayments_idcardPayments`)
    REFERENCES `oficina`.`cardPayments` (`idcardPayments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`os` (
  `idos` INT NOT NULL,
  `status` ENUM('completo', 'em andamento', 'não iniciado') NULL DEFAULT 'não iniciado',
  `datainicio` DATETIME NULL DEFAULT NULL,
  `datafim` DATETIME NULL DEFAULT NULL,
  `valortotal` FLOAT NULL DEFAULT NULL,
  `payments_idpayments` INT NOT NULL,
  PRIMARY KEY (`idos`, `payments_idpayments`),
  INDEX `fk_os_payments1_idx` (`payments_idpayments` ASC) VISIBLE,
  CONSTRAINT `fk_os_payments1`
    FOREIGN KEY (`payments_idpayments`)
    REFERENCES `oficina`.`payments` (`idpayments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`cliente` (
  `idcliente` INT NOT NULL,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `cpf` INT(12) NULL DEFAULT NULL,
  `endereço` VARCHAR(255) NULL DEFAULT NULL,
  `contato` INT NOT NULL,
  `payments_idpayments` INT NOT NULL,
  PRIMARY KEY (`idcliente`, `payments_idpayments`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_cliente_payments1_idx` (`payments_idpayments` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_payments1`
    FOREIGN KEY (`payments_idpayments`)
    REFERENCES `oficina`.`payments` (`idpayments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`mecanicos` (
  `idmecanicos` INT NOT NULL,
  `salario` FLOAT NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `endereço` VARCHAR(45) NULL DEFAULT NULL,
  `especialidade` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmecanicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`servico` (
  `idservico` INT NOT NULL,
  `mecanicos_idmecanicos` INT NOT NULL,
  `type_service` ENUM('reparo', 'adição', 'vistoria') NULL DEFAULT 'vistoria',
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idservico`, `mecanicos_idmecanicos`),
  INDEX `fk_servico_mecanicos1_idx` (`mecanicos_idmecanicos` ASC) VISIBLE,
  CONSTRAINT `fk_servico_mecanicos1`
    FOREIGN KEY (`mecanicos_idmecanicos`)
    REFERENCES `oficina`.`mecanicos` (`idmecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`veiculo` (
  `idveiculo` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `placa` VARCHAR(45) NULL DEFAULT NULL,
  `objetivo` VARCHAR(255) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idveiculo`, `cliente_idcliente`),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Cliente possui veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`Cliente possui veiculo` (
  `cliente_idcliente` INT NOT NULL,
  `veiculo_idveiculo` INT NOT NULL,
  PRIMARY KEY (`cliente_idcliente`, `veiculo_idveiculo`),
  INDEX `fk_cliente_has_veiculo_veiculo1_idx` (`veiculo_idveiculo` ASC) VISIBLE,
  INDEX `fk_cliente_has_veiculo_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_veiculo_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `oficina`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_veiculo_veiculo1`
    FOREIGN KEY (`veiculo_idveiculo`)
    REFERENCES `oficina`.`veiculo` (`idveiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Gera OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`Gera OS` (
  `veiculo_idveiculo` INT NOT NULL,
  `os_idos` INT NOT NULL,
  PRIMARY KEY (`veiculo_idveiculo`, `os_idos`),
  INDEX `fk_veiculo_has_os_os1_idx` (`os_idos` ASC) VISIBLE,
  INDEX `fk_veiculo_has_os_veiculo1_idx` (`veiculo_idveiculo` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_has_os_veiculo1`
    FOREIGN KEY (`veiculo_idveiculo`)
    REFERENCES `oficina`.`veiculo` (`idveiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_has_os_os1`
    FOREIGN KEY (`os_idos`)
    REFERENCES `oficina`.`os` (`idos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`peça`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`peça` (
  `idpeça` INT NOT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idpeça`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`peça para os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`peça para os` (
  `os_idos` INT NOT NULL,
  `peça_idpeça` INT NOT NULL,
  PRIMARY KEY (`os_idos`, `peça_idpeça`),
  INDEX `fk_os_has_peça_peça1_idx` (`peça_idpeça` ASC) VISIBLE,
  INDEX `fk_os_has_peça_os1_idx` (`os_idos` ASC) VISIBLE,
  CONSTRAINT `fk_os_has_peça_os1`
    FOREIGN KEY (`os_idos`)
    REFERENCES `oficina`.`os` (`idos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_has_peça_peça1`
    FOREIGN KEY (`peça_idpeça`)
    REFERENCES `oficina`.`peça` (`idpeça`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oficina`.`Serviço da OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oficina`.`Serviço da OS` (
  `os_idos` INT NOT NULL,
  `servico_idservico` INT NOT NULL,
  PRIMARY KEY (`os_idos`, `servico_idservico`),
  INDEX `fk_os_has_servico_servico1_idx` (`servico_idservico` ASC) VISIBLE,
  INDEX `fk_os_has_servico_os1_idx` (`os_idos` ASC) VISIBLE,
  CONSTRAINT `fk_os_has_servico_os1`
    FOREIGN KEY (`os_idos`)
    REFERENCES `oficina`.`os` (`idos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_os_has_servico_servico1`
    FOREIGN KEY (`servico_idservico`)
    REFERENCES `oficina`.`servico` (`idservico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;