-- MySQL Script generated by MySQL Workbench
-- Fri Sep 16 19:41:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommercedio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommercedio` ;

-- -----------------------------------------------------
-- Schema ecommercedio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommercedio` DEFAULT CHARACTER SET utf8 ;
USE `ecommercedio` ;

-- -----------------------------------------------------
-- Table `ecommercedio`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Campus` VARCHAR(45) NOT NULL,
  `idProfessor_coordenador` INT NOT NULL,
  PRIMARY KEY (`idDepartamento`, `idProfessor_coordenador`),
  INDEX `fk_Departamento_Professor1_idx` (`idProfessor_coordenador` ASC) VISIBLE,
  CONSTRAINT `fk_Departamento_Professor1`
    FOREIGN KEY (`idProfessor_coordenador`)
    REFERENCES `ecommercedio`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Pessoa` (
  `idPessoa` INT NOT NULL,
  `Nomel` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`Período`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Período` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Período` (
  `idPeríodo` INT NOT NULL,
  `Ano` VARCHAR(45) NULL,
  `Semestre` VARCHAR(45) NULL,
  PRIMARY KEY (`idPeríodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Produto` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Produto` (
  `idProduto` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Categoria` VARCHAR(45) NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Produto_idProduto` INT NOT NULL,
  `Identificação` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL COMMENT 'atributo constituido por rua, bairro, complemento, cidade, estado e cep',
  PRIMARY KEY (`idCliente`, `Produto_idProduto`),
  INDEX `fk_Cliente_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommercedio`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Estoque` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `Local` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `Razão Social` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`pix`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`pix` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`pix` (
  `idpix` INT NOT NULL,
  `chave_pix` VARCHAR(45) NULL,
  `descrição` VARCHAR(45) NULL,
  PRIMARY KEY (`idpix`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`card_number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`card_number` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`card_number` (
  `idcard_number` INT NOT NULL,
  `name_card` VARCHAR(45) NULL,
  `type_card` VARCHAR(45) NULL,
  PRIMARY KEY (`idcard_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`deposito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`deposito` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`deposito` (
  `iddeposito` INT NOT NULL,
  `titular` VARCHAR(45) NULL,
  `number_bank` VARCHAR(45) NULL,
  `agencia` VARCHAR(45) NULL,
  `conta` VARCHAR(45) NULL,
  PRIMARY KEY (`iddeposito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`pagamento` (
  `idpagamento` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `cpf_ou_cnpj` VARCHAR(45) NULL,
  `Nome Cliente` VARCHAR(45) NULL,
  `pix_idpix` INT NOT NULL,
  `card_number_idcard_number` INT NOT NULL,
  `deposito_iddeposito` INT NOT NULL,
  PRIMARY KEY (`idpagamento`, `pix_idpix`, `card_number_idcard_number`, `deposito_iddeposito`),
  INDEX `fk_pagamento_pix1_idx` (`pix_idpix` ASC) VISIBLE,
  INDEX `fk_pagamento_card_number1_idx` (`card_number_idcard_number` ASC) VISIBLE,
  INDEX `fk_pagamento_deposito1_idx` (`deposito_iddeposito` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_pix1`
    FOREIGN KEY (`pix_idpix`)
    REFERENCES `ecommercedio`.`pix` (`idpix`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_card_number1`
    FOREIGN KEY (`card_number_idcard_number`)
    REFERENCES `ecommercedio`.`card_number` (`idcard_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_deposito1`
    FOREIGN KEY (`deposito_iddeposito`)
    REFERENCES `ecommercedio`.`deposito` (`iddeposito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Entrega` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Entrega` (
  `idEntrega` INT NOT NULL,
  `status_entrega` VARCHAR(45) NULL,
  `codigo_rastreio` VARCHAR(45) NULL,
  PRIMARY KEY (`idEntrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Pedido` (
  `idPedido` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `Descrição` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Frete` FLOAT NULL,
  `pagamento_idpagamento` INT NOT NULL,
  `Entrega_idEntrega` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`, `pagamento_idpagamento`, `Entrega_idEntrega`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedido_pagamento1_idx` (`pagamento_idpagamento` ASC) VISIBLE,
  INDEX `fk_Pedido_Entrega1_idx` (`Entrega_idEntrega` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `ecommercedio`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_pagamento1`
    FOREIGN KEY (`pagamento_idpagamento`)
    REFERENCES `ecommercedio`.`pagamento` (`idpagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Entrega1`
    FOREIGN KEY (`Entrega_idEntrega`)
    REFERENCES `ecommercedio`.`Entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`Relação de produto por pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Relação de produto por pedido` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Relação de produto por pedido` (
  `Produto_idProduto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Pedido_idPedido`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommercedio`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `ecommercedio`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`pessoa_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`pessoa_juridica` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`pessoa_juridica` (
  `idpessoa_juridica` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpessoa_juridica`, `Cliente_idCliente`),
  INDEX `fk_pessoa_juridica_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_juridica_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `ecommercedio`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`pessoa_fisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`pessoa_fisica` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`pessoa_fisica` (
  `idpessoa_fisica` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpessoa_fisica`, `Cliente_idCliente`),
  INDEX `fk_pessoa_fisica_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_fisica_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `ecommercedio`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`Disponibilizando um produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Disponibilizando um produto` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Disponibilizando um produto` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Produto_idProduto`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Produto_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `ecommercedio`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommercedio`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`Produto_has_Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Produto_has_Estoque` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Produto_has_Estoque` (
  `Produto_idProduto` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Estoque_idEstoque`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  INDEX `fk_Produto_has_Estoque_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommercedio`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `ecommercedio`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`Terceiro - Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Terceiro - Vendedor` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Terceiro - Vendedor` (
  `idTerceiro - Vendedor` INT NOT NULL,
  `Razão Social` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  PRIMARY KEY (`idTerceiro - Vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommercedio`.`Produtos por vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommercedio`.`Produtos por vendedor` ;

CREATE TABLE IF NOT EXISTS `ecommercedio`.`Produtos por vendedor` (
  `Terceiro - Vendedor_idTerceiro - Vendedor` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Terceiro - Vendedor_idTerceiro - Vendedor`, `Produto_idProduto`),
  INDEX `fk_Terceiro - Vendedor_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Terceiro - Vendedor_has_Produto_Terceiro - Vendedor1_idx` (`Terceiro - Vendedor_idTerceiro - Vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_Terceiro - Vendedor_has_Produto_Terceiro - Vendedor1`
    FOREIGN KEY (`Terceiro - Vendedor_idTerceiro - Vendedor`)
    REFERENCES `ecommercedio`.`Terceiro - Vendedor` (`idTerceiro - Vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terceiro - Vendedor_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `ecommercedio`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



